link_parsing:
    profs: [
    'frontend', 'backend', 'data scientist', 'ML engineer',
    'data analyst', 'web developer', 'QA engineer', 'test engineer', 'devops'
]
    titles: [
    '', 'lead', 'senior', 'middle'
]
    init_page: 1 #int, > 0
    page_pass: 1 #int, > 0
    time_base: 5
post_parsing:
    limit_low: 2600 #int, >= 0
    limit_high: 2650 #int, > 0
    time_base: 4