link_parsing:
    profs: [
    'frontend', 'backend', 'data scientist', 'ML engineer',
    'data analyst', 'web developer', 'QA engineer', 'test engineer', 'devops'
]
    titles: [
    'lead', 'senior', 'middle'
]
    page_num: 19